name: Release to NPM
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

concurrency:
  group: 'release-npm'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:wc
      - run: cd packages/ai-chat-components && npx semantic-release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Need owner/admin account to bypass branch protection
          GIT_COMMITTER_NAME: sinedied
          GIT_COMMITTER_EMAIL: noda@free.fr
